### ISSUE TITLE
Checking for registration too often.

### ISSUE THREAD

**Issue by barthballard** [orschiro/AltQ#42]
I donated/paid for this app but it seems to be checking for payment authentication every 4th or 5th time I try to use it. Can this be reduced or eliminated?

**Comment by orschiro** [comment]
@barthballard thanks for your support. What do you mean by checking for authentication?

Are you seeing a pop-up or what exactly is disturbing you?

**Comment by barthballard** [comment]
Thanks for responding. yes, it's a pop-up that confirms payment instead of switching tabs.

**Comment by orschiro** [comment]
Very strange. Which OS, browser and version are you using?

I am going to try to reproduce it.

**Comment by barthballard** [comment]
Mac OS 12 and Chrome Version 111.0.5563.64 . It doesn't happen every time but several times per week

**Comment by orschiro** [comment]
Thanks. Do you see a specific pattern when it occurs?

Immediately after the start of the computer or after suspend and with
connecting network connection?

**Comment by barthballard** [comment]
I haven't noticed a pattern. How often is it supposed to check for payment confirmation for the extension?

**Comment by orschiro** [comment]
It should only show you a confirmation pop-up once after install and then
never again.

Can you do me a favor and record a small video next time it happens,
detailing the exact situation as to what happened right before?
