### ISSUE TITLE
Access Requested Issue

### ISSUE THREAD

**Issue by leem83** [orschiro/AltQ#44]
It seems that after the last chrome update, switching tabs does not work for sites that are inactive for some time. When I click on one of these tabs, I see that chrome shows the  Switch Last Tab extension in a "Access Requested" section of the extension manager (see screenshot below). Once I click on the tab and it becomes active, the extension no longer shows up on the "Access Requested" section and it works as intended. This seems to be new behavior. Would be great to adjust the extension such that it can still switch to the last tab even if it is inactive. 

<img width="331" alt="image" src="https://github.com/orschiro/AltQ/assets/2976445/8962bfbd-5ee7-4e32-af2d-bd416474639f">

**Comment by orschiro** [comment]
Thanks Lee!

Should have already been fixed in v48.1.

Currently pending review in the store.

24 Feb 2024 01:05:41 Lee Maliniak ***@***.***>:

**Comment by orschiro** [comment]
Lee, have you noticed an improvement with version 48.1?

**Comment by leem83** [comment]
It still seems to be an issue. I have verified that the extension is the latest 48.1 build. If I don't go to the last tab for some amount of time, when I do the hot key, it will not switch to the last tab. If click on the tab and engage with it, then the hot key starts working again. I have tried to capture a video of it. Hope this helps: https://app.screencast.com/7iAA5S8QFxwV2

**Comment by orschiro** [comment]
Bummer. 

What about version 49?

[49.zip](https://github.com/orschiro/AltQ/files/14410024/49.zip)

**Comment by leem83** [comment]
Seems to work. I will use it for a bit today and let you know if i find a use case where it does not work. https://app.screencast.com/WMEM90g5apby7

**Comment by orschiro** [comment]
Please do, thanks!

If you don't encounter any more issues, I am going to publish it to the
store tomorrow. :)

**Comment by orschiro** [comment]
Very glad to hear! :)

Mind leaving me a written review on the extension store?

That would be much appreciated!

27 Feb 2024 01:06:18 Lee Maliniak ***@***.***>:
