### ISSUE TITLE
Feels like you're losing your memory if more than a minute passes

### ISSUE THREAD

**Issue by ofmarconi** [orschiro/AltQ#45]
When I'm reading a page, it seems like the memory of the previous tab seems to erase very quickly, do you have any idea what it could be?

I recently installed an extension, it may be incompatible with https://chrome.google.com/webstore/detail/nbokbjkabcmbfdlbddjidfmibcpneigj

**Comment by orschiro** [comment]
@ofmarconi can you please try attached version 48.2?

[48-2.zip](https://github.com/orschiro/AltQ/files/14409145/48-2.zip)

**Comment by eskp** [comment]
Have noticed the issue recently as well. Will try the provided version. Thanks

**Comment by orschiro** [comment]
@eskp @ofmarconi 48.2 won't yet fix your problem. 

Please try version 49.

Does it work?

[49.zip](https://github.com/orschiro/AltQ/files/14415808/49.zip)

**Comment by eskp** [comment]
You're right, 48.2 did not. Will try 49 now.

**Comment by orschiro** [comment]
Please do and report back, thank you!

**Comment by eskp** [comment]
I don't see your email address, can you please share it again

**Comment by orschiro** [comment]
orschiro at gmail dot com

**Comment by orschiro** [comment]
@ofmarconi @eskp version 49 has been published in the store.

Can you please confirm that it's solving your issues?

Thank you!

**Comment by eskp** [comment]
Solved for me! Thanks 🙏

**Comment by orschiro** [comment]
@eskp thanks!

@ofmarconi how about you?

**Comment by orschiro** [comment]
Closing as fixed by version 49.

**Comment by ofmarconi** [comment]
@orschiro 
Solved for me to! Thanks 🙏

**Comment by orschiro** [comment]
Glad to hear!

Could you leave me a written review on the webstore?

That would be very kind of you!

5 Mar 2024 12:30:35 Orlando Marconi ***@***.***>:

**Comment by orschiro** [comment]
Thank you!

**Comment by orschiro** [comment]
@ofmarconi here is the direct link in case you need it: https://chromewebstore.google.com/detail/switch-last-tabs/odhjcgnlbagjllfbilicalpigimhdcll/reviews

**Comment by ofmarconi** [comment]
[image: image.png]
I had already rated it 5 stars before, I can only edit.



*_ Marconi*


Em qui., 7 de mar. de 2024 às 04:21, Robert Orzanna <
***@***.***> escreveu:

**Comment by orschiro** [comment]
Much appreciated, thank you! :)
